builds:
  - binary: bff
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-w -s -X main.Date={{.CommitDate}} -X github.com/chanzuckerberg/bff/pkg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/bff/pkg/util.Version={{.Version}} -X github.com/chanzuckerberg/bff/pkg/util.Dirty=false -X github.com/chanzuckerberg/bff/pkg/util.Release=true"
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - files:
    - none*

release:
  github:
    owner: chanzuckerberg
    name: bff

brews:
  -
    description: "Breaking, Feature, Fix - a tool for managing semantic versioning"
    github:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/bff"
    test: system "#{bin}/bff version"
