dist: bionic
language: go
go:
  - "1.13.1"
install:
  - npm install -g snyk
jobs:
  include:
    - stage: check
      script:
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: check
      script:
        - snyk monitor --org=czi
        - snyk test
