[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.7.1"

[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/segmentio/go-prompt"
  branch = "master"